dist: xenial
language: python
python: 3.7
cache: pypi

install:
  - pip install flake8 codecov pytest pytest-cov

script:
  - python3.7 -m flake8 my_tests/
  - python3.7 -m pytest -vvv my_tests/ --cov my_tests

after_success:
  -codecov f4feb000-42fc-4505-a259-a86ad91cb815
  
branches:
  only:
  - master
