dist: xenial
language: python
python: 3.7
cache: pypi

install:
  - pip install flake8 codecov pytest pytest-cov

script:
  - python3.7 -m flake8 Game/
  - python3.7 -m pytest -vvv my_tests/ --cov=Game

after_success:
  - codecov
  
branches:
  only:
  - master
